In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
from sklearn.datasets import make_classification

In [45]:
X,y=make_classification(n_samples=5000,n_features=10,n_classes=2,random_state=42)

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
X

array([[ 1.86419953, -2.3711592 , -0.67130759, ..., -0.67354431,
        -0.69646109, -0.07686541],
       [ 0.33548674,  0.27130442, -2.02015145, ...,  0.31740948,
         0.38546963,  0.13372972],
       [ 0.14663259, -1.54427911,  0.59252101, ..., -0.20558104,
        -1.03009508, -0.65817527],
       ...,
       [-1.06725502,  1.3232629 ,  0.40885419, ..., -0.03644982,
        -1.3116659 , -2.0157712 ],
       [ 1.21249094, -1.28557149, -0.81813422, ..., -1.84190565,
         0.39546944, -1.16454678],
       [ 0.02000132, -1.05592707,  1.88566879, ..., -1.8550231 ,
         0.17599725, -0.36139164]], shape=(5000, 10))

In [48]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9
0,1.864200,-2.371159,-0.671308,-0.666403,1.313473,0.089198,-2.025296,-0.673544,-0.696461,-0.076865
1,0.335487,0.271304,-2.020151,-0.026345,1.237954,-0.821913,-0.135680,0.317409,0.385470,0.133730
2,0.146633,-1.544279,0.592521,-0.533506,2.098841,0.630108,-1.675337,-0.205581,-1.030095,-0.658175
3,1.381038,0.580438,0.592245,0.070211,-0.236920,-0.183078,0.163010,0.382557,-0.485876,-2.627336
4,1.909303,1.454931,0.215403,0.426089,0.365654,-0.289065,1.304263,0.373018,-1.217340,0.650181
...,...,...,...,...,...,...,...,...,...,...
4995,-1.869980,-0.456454,0.690073,0.172400,-0.291520,-0.709841,0.686945,-0.834066,-0.350569,1.752429
4996,1.485217,-0.521684,1.117632,-0.096900,-0.772509,0.501852,-0.267543,-0.264658,0.739759,-0.342994
4997,-1.067255,1.323263,0.408854,0.547905,1.358744,0.539942,1.760576,-0.036450,-1.311666,-2.015771
4998,1.212491,-1.285571,-0.818134,0.269055,-0.488136,-2.033299,1.159407,-1.841906,0.395469,-1.164547


In [49]:
y

array([0, 0, 1, ..., 1, 1, 0], shape=(5000,))

In [50]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [51]:
from sklearn.linear_model import LogisticRegression

In [52]:
logistic=LogisticRegression()

In [53]:
logistic.fit(X_train,y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

In [54]:
y_pred=logistic.predict(X_test)

In [55]:
logistic.predict_proba(X_test)

array([[0.11442096, 0.88557904],
       [0.98544932, 0.01455068],
       [0.02281525, 0.97718475],
       ...,
       [0.04970537, 0.95029463],
       [0.95682967, 0.04317033],
       [0.98305135, 0.01694865]], shape=(1500, 2))

In [56]:
y_pred

array([1, 0, 1, ..., 1, 0, 0], shape=(1500,))

In [57]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score

In [58]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)
confusion=confusion_matrix(y_test,y_pred)
print(confusion)
precision=precision_score(y_test,y_pred)
print(precision)
recall=recall_score(y_test,y_pred)
print(recall)

0.878
[[658 100]
 [ 83 659]]
0.8682476943346509
0.8881401617250674


In [59]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedGroupKFold

model=logistic
penalty=['l1', 'l2', 'elasticnet']
c_value=[1000,100,0.1,0.01]
solver=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']


In [60]:
params=dict(penalty=penalty,C=c_value,solver=solver)

In [61]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [1000, 100, 0.1, 0.01],
 'solver': ['lbfgs',
  'liblinear',
  'newton-cg',
  'newton-cholesky',
  'sag',
  'saga']}

In [62]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

grid = GridSearchCV(
    estimator=model,
    param_grid=params,
    scoring="accuracy",
    cv=cv
)

grid.fit(X_train, y_train)

c:\Users\manas\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\manas\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(


,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",LogisticRegression()
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'C': [1000, 100, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['lbfgs', 'liblinear', ...]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion <scoring_api_overview>` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'accuracy'
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- an iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide <cross_validation>` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",StratifiedKFo... shuffle=True)
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",None
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example<sphx_glr_auto_examples_model_selection_plot_grid_search_refit_callable.py>`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"verbose ve

In [63]:
print(cv)
print(type(cv))
print(X_train.shape)
print(y_train.shape)

StratifiedKFold(n_splits=5, random_state=42, shuffle=True)
<class 'sklearn.model_selection._split.StratifiedKFold'>
(3500, 10)
(3500,)


In [64]:
grid.fit(X_train, y_train)

print(grid.best_params_)
print(grid.best_score_)

c:\Users\manas\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\manas\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(


{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}
0.8605714285714285
