In [33]:
!pip install numpy

In [34]:
import numpy as np

In [35]:
## 1d matrix
arr=np.array([1,2,3,4,5])
print(arr)#prints array
print(arr.shape)#gives number of rows and columns
print(arr.reshape(1,5))#reshapes into number of rows and colums
#print(arr.reshape(1,4))#ValueError: cannot reshape array of size 5 into shape (1,4) because we have 5 vales in a row so the colums number must be 5 as well

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]]


In [36]:
##2d array
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)
print(arr1.itemsize)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
8
int64
8


In [ ]:
np.ones((3,4))#takes input a tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
np.arange(0,10,2)#start,end,step

array([0, 2, 4, 6, 8])

In [43]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [ ]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
## element wise mathematical operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print("addition:",arr1+arr2)
print("substraction:",arr2-arr1)
print("multiplication:",arr2*arr1)
print("division:",arr2/arr1)

addition: [11 22 33 44 55]
substraction: [ 9 18 27 36 45]
multiplication: [ 10  40  90 160 250]
division: [10. 10. 10. 10. 10.]


In [58]:
##universal functions
arr3=np.array([1,2,3,4,5,6])
print("squares:",np.sqrt(arr3))
print("exponent:",np.exp(arr3))
print("sine:",np.sin(arr3))
print("natural log:",np.log(arr3))

squares: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
exponent: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
natural log: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
#slicing and indexing in an array
arr4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [63]:
arr4[0:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [65]:
arr4[0,1]

np.int64(2)

In [66]:
arr4[1:,0:2]

array([[ 5,  6],
       [ 9, 10]])

In [67]:
arr4[0,0]=100
print(arr4)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [68]:
arr4[1:]=100
print(arr4)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
#statistical operations -->normalization and standard deviation
data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_deviation=np.std(data)
normalized_data=(data-mean)/std_deviation
print("normalized data:",normalized_data)


normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [75]:
#mean median  standard deviation variance
data1=np.array([1,2,3,4,5,6,7,8,9,10])
print("mean:",np.mean(data1))
print("median:",np.median(data1))
print("standard deviation:",np.std(data1))
print("var:",np.var(data1))

mean: 5.5
median: 5.5
standard deviation: 2.8722813232690143
var: 8.25


In [ ]:
#logical operations
data1>5 #return a list of boolean

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
data1[data1>5] #creates an array

array([ 6,  7,  8,  9, 10])

In [83]:
data1[(data1>5) & (data1<8)] #only logical operators are used

array([6, 7])

In [84]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [86]:
np.random.randint(1,10,5)

array([8, 8, 9, 5, 4], dtype=int32)

In [88]:

np.random.rand(2,2)



array([[0.78889292, 0.61132781],
       [0.11304457, 0.96148641]])

In [89]:
arr.flatten()

array([1, 2, 3, 4, 5])

In [92]:
np.min(arr)

np.int64(1)

In [91]:
np.max(arr)

np.int64(5)

In [93]:
np.sum(arr)

np.int64(15)

In [95]:
np.sort(arr)

array([1, 2, 3, 4, 5])

In [96]:
np.argmax(arr)

np.int64(4)

In [98]:

np.argmin(arr)


np.int64(0)

In [99]:

np.where(arr > 5)

(array([], dtype=int64),)